services:

  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=${POSTGRES_DB}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    networks:
      - adndnetwork

  app:
    build:
      context: .
    ports:
      - '${API_PORT}:8080'
    depends_on:
      - postgres
    networks:
      - adndnetwork
    env_file: .env

networks:
  adndnetwork:
    driver: bridge