services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=${POSTGRES_DB}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    networks:
      - apinetwork

  adedapi:
    build:
      context: .
    expose:
      - 8080
    ports:
      - '${PORT}:8080'
    depends_on:
      - postgres
    networks:
      - apinetwork
    env_file: .env

networks:
  apinetwork:
    driver: bridge